//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobsearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComRegTab
    {
        public int Comid { get; set; }
        public string ComName { get; set; }
        public string ComAddress { get; set; }
        public string ComEmail { get; set; }
        public string ComPhone { get; set; }
        public string ComWebsite { get; set; }
    }
}
