//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobsearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAppTab
    {
        public int Appid { get; set; }
        public int Usid { get; set; }
        public int Jobid { get; set; }
        public string Resume { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
    }
}
