//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobsearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTab
    {
        public int Jobid { get; set; }
        public int Comid { get; set; }
        public string JobTittle { get; set; }
        public string JobDesc { get; set; }
        public string JobSkills { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
    }
}
