//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobsearch
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProjectmvcEntities : DbContext
    {
        public ProjectmvcEntities()
            : base("name=ProjectmvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComRegTab> ComRegTabs { get; set; }
        public virtual DbSet<JobAppTab> JobAppTabs { get; set; }
        public virtual DbSet<JobTab> JobTabs { get; set; }
        public virtual DbSet<LoginTab> LoginTabs { get; set; }
        public virtual DbSet<UsRegTab> UsRegTabs { get; set; }
    
        public virtual int sp_comRegTab(Nullable<int> cid, string cna, string cadr, string cemail, string cphone, string cwebsite)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var cnaParameter = cna != null ?
                new ObjectParameter("cna", cna) :
                new ObjectParameter("cna", typeof(string));
    
            var cadrParameter = cadr != null ?
                new ObjectParameter("cadr", cadr) :
                new ObjectParameter("cadr", typeof(string));
    
            var cemailParameter = cemail != null ?
                new ObjectParameter("cemail", cemail) :
                new ObjectParameter("cemail", typeof(string));
    
            var cphoneParameter = cphone != null ?
                new ObjectParameter("cphone", cphone) :
                new ObjectParameter("cphone", typeof(string));
    
            var cwebsiteParameter = cwebsite != null ?
                new ObjectParameter("cwebsite", cwebsite) :
                new ObjectParameter("cwebsite", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_comRegTab", cidParameter, cnaParameter, cadrParameter, cemailParameter, cphoneParameter, cwebsiteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MaxIdLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MaxIdLogin");
        }
    
        public virtual int sp_Loginsert(Nullable<int> rid, string una, string pw, string utype)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwParameter = pw != null ?
                new ObjectParameter("pw", pw) :
                new ObjectParameter("pw", typeof(string));
    
            var utypeParameter = utype != null ?
                new ObjectParameter("utype", utype) :
                new ObjectParameter("utype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Loginsert", ridParameter, unaParameter, pwParameter, utypeParameter);
        }
    
        public virtual int sp_userReg(Nullable<int> uid, string na, Nullable<int> ag, string adr, string phn, string eml, string pho, string skl, string expy, string loc, string qual)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var naParameter = na != null ?
                new ObjectParameter("na", na) :
                new ObjectParameter("na", typeof(string));
    
            var agParameter = ag.HasValue ?
                new ObjectParameter("ag", ag) :
                new ObjectParameter("ag", typeof(int));
    
            var adrParameter = adr != null ?
                new ObjectParameter("adr", adr) :
                new ObjectParameter("adr", typeof(string));
    
            var phnParameter = phn != null ?
                new ObjectParameter("phn", phn) :
                new ObjectParameter("phn", typeof(string));
    
            var emlParameter = eml != null ?
                new ObjectParameter("eml", eml) :
                new ObjectParameter("eml", typeof(string));
    
            var phoParameter = pho != null ?
                new ObjectParameter("pho", pho) :
                new ObjectParameter("pho", typeof(string));
    
            var sklParameter = skl != null ?
                new ObjectParameter("skl", skl) :
                new ObjectParameter("skl", typeof(string));
    
            var expyParameter = expy != null ?
                new ObjectParameter("expy", expy) :
                new ObjectParameter("expy", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var qualParameter = qual != null ?
                new ObjectParameter("qual", qual) :
                new ObjectParameter("qual", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userReg", uidParameter, naParameter, agParameter, adrParameter, phnParameter, emlParameter, phoParameter, sklParameter, expyParameter, locParameter, qualParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LoginCountId(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LoginCountId", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LoginId(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LoginId", unaParameter, pwdParameter);
        }
    
        public virtual ObjectResult<string> sp_LoginType(string una, string pwd)
        {
            var unaParameter = una != null ?
                new ObjectParameter("una", una) :
                new ObjectParameter("una", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_LoginType", unaParameter, pwdParameter);
        }
    
        public virtual int sp_Jobinsert(Nullable<int> cid, string jttl, string jdes, string jskl, Nullable<System.DateTime> edate, string sts)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var jttlParameter = jttl != null ?
                new ObjectParameter("jttl", jttl) :
                new ObjectParameter("jttl", typeof(string));
    
            var jdesParameter = jdes != null ?
                new ObjectParameter("jdes", jdes) :
                new ObjectParameter("jdes", typeof(string));
    
            var jsklParameter = jskl != null ?
                new ObjectParameter("jskl", jskl) :
                new ObjectParameter("jskl", typeof(string));
    
            var edateParameter = edate.HasValue ?
                new ObjectParameter("edate", edate) :
                new ObjectParameter("edate", typeof(System.DateTime));
    
            var stsParameter = sts != null ?
                new ObjectParameter("sts", sts) :
                new ObjectParameter("sts", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Jobinsert", cidParameter, jttlParameter, jdesParameter, jsklParameter, edateParameter, stsParameter);
        }
    
        public virtual int sp_Jobsearchs(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Jobsearchs", qryParameter);
        }
    
        public virtual ObjectResult<sp_jobstab_Result> sp_jobstab()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_jobstab_Result>("sp_jobstab");
        }
    
        public virtual int sp_Jobsearching(string qry)
        {
            var qryParameter = qry != null ?
                new ObjectParameter("qry", qry) :
                new ObjectParameter("qry", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Jobsearching", qryParameter);
        }
    
        public virtual int sp_resumApply(Nullable<int> uid, Nullable<int> jid, string resm, string sts, Nullable<System.DateTime> dat)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var jidParameter = jid.HasValue ?
                new ObjectParameter("jid", jid) :
                new ObjectParameter("jid", typeof(int));
    
            var resmParameter = resm != null ?
                new ObjectParameter("resm", resm) :
                new ObjectParameter("resm", typeof(string));
    
            var stsParameter = sts != null ?
                new ObjectParameter("sts", sts) :
                new ObjectParameter("sts", typeof(string));
    
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_resumApply", uidParameter, jidParameter, resmParameter, stsParameter, datParameter);
        }
    
        public virtual int sp_resumeApply(Nullable<int> uid, Nullable<int> joid, string resm, string sts, Nullable<System.DateTime> dat)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            var joidParameter = joid.HasValue ?
                new ObjectParameter("joid", joid) :
                new ObjectParameter("joid", typeof(int));
    
            var resmParameter = resm != null ?
                new ObjectParameter("resm", resm) :
                new ObjectParameter("resm", typeof(string));
    
            var stsParameter = sts != null ?
                new ObjectParameter("sts", sts) :
                new ObjectParameter("sts", typeof(string));
    
            var datParameter = dat.HasValue ?
                new ObjectParameter("dat", dat) :
                new ObjectParameter("dat", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_resumeApply", uidParameter, joidParameter, resmParameter, stsParameter, datParameter);
        }
    }
}
